#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Set background to black
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/reset.jpg
fi

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

pkill compton 
pkill polybar

